#!/bin/bash
# IPs
ifconfig enp0s3 192.168.1.30 netmask 255.255.255.0 up
ip route add 10.0.20.0/24 via 192.168.1.40

# Wireguard
ip link add wg0 type wireguard
ip addr add 10.0.0.30/24 dev wg0
wg set wg0 listen-port 39198 private-key /home/ubuntu/.ssh/wg_private
ip link set wg0 up
wg set wg0 peer 6ejIgrueSPwWZ9ZFtb0kckmWqHBRctP1fVCb4T6W4yk= allowed-ips 10.0.0.10 endpoint 192.168.1.10:55027

# NAT connection coming from VPN
sysctl -w net.ipv4.ip_forward=1

# IP tables
iptables -F
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Allow to SSH internal network through VPN tunnel
iptables -A FORWARD -i wg0 -j ACCEPT
iptables -A FORWARD -o wg0 -j ACCEPT
iptables -A INPUT -i enp0s3 -p udp --dport 39198 -j ACCEPT
iptables -A INPUT -i wg0 -j ACCEPT
iptables -A OUTPUT -o enp0s3 -p udp --dport 55027 -j ACCEPT
iptables -A OUTPUT -o enp0s3 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -o wg0 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.0.0.10 -o enp0s3 -j MASQUERADE

# Allow SSH the VPN from outside world
iptables -A INPUT -i enp0s3 -d 192.168.1.30 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -s 192.168.1.30 -p tcp --sport 22 -j ACCEPT

#Allow SFTP connetions to Backup Server
iptables -A INPUT -i enp0s3 -s 10.0.20.50 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -d 10.0.20.50 -p tcp --sport 22 -j ACCEPT