#!/bin/bash
# IPs
ifconfig enp0s3 10.0.20.20 netmask 255.255.255.0 up
ip route add 192.168.1.0/24 via 10.0.20.40

# IP tables
# Internal Firewall
iptables -F
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Allow SSH from VPN
iptables -A INPUT -i enp0s3 -s 192.168.1.30 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -d 192.168.1.30 -p tcp --sport 22 -j ACCEPT

# Allow HTTPS access from Core
iptables -A INPUT -i enp0s3 -s 10.0.20.10 -p tcp --dport 10443 -j ACCEPT
iptables -A OUTPUT -d 10.0.20.10 -o enp0s3 -p tcp --sport 10443 -j ACCEPT

#Allow SFTP connetions to Backup Server
iptables -A INPUT -i enp0s3 -s 10.0.20.50 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -d 10.0.20.50 -p tcp --sport 22 -j ACCEPT

python3 /var/www/ca/flask_server.py > /var/log/Flask.log 2>&1 