#!/bin/bash
# IPs
ifconfig enp0s3 10.0.20.10 netmask 255.255.255.0 up
ifconfig enp0s8 10.0.10.10 netmask 255.255.255.0 up
ip route add 192.168.1.0/24 via 10.0.10.40
ip route add 192.168.1.30/32 via 10.0.20.40

# IP tables
iptables -F
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Allow HTTPS connection from Webserver
iptables -A INPUT -i enp0s8 -s 192.168.1.20 -d 10.0.10.10 -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -s 10.0.10.10 -d 192.168.1.20 -p tcp --sport 443 -j ACCEPT

# Allow SSH from VPN server
iptables -A INPUT -i enp0s3 -s 192.168.1.30 -d 10.0.20.10 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -d 192.168.1.30 -s 10.0.20.10 -p tcp --sport 22 -j ACCEPT

# Allow HTTPS connection with MySQL
iptables -A INPUT -i enp0s3 -s 10.0.20.30 -d 10.0.20.10 -p tcp --sport 443 -j ACCEPT
iptables -A OUTPUT -s 10.0.20.10 -d 10.0.20.30 -p tcp --dport 443 -j ACCEPT

# Allow HTTPS with CA server
iptables -A INPUT -i enp0s3 -s 10.0.20.20 -d 10.0.20.10 -p tcp --sport 443 -j ACCEPT
iptables -A OUTPUT -d 10.0.20.20 -p tcp --dport 443 -j ACCEPT

# Allow Localhost
iptables -A INPUT -s 127.0.0.1 -j ACCEPT
iptables -A OUTPUT -d 127.0.0.1 -j ACCEPT

#Allow SFTP connetions to Backup Server
iptables -A INPUT -i enp0s3 -s 10.0.20.50 -d 10.0.20.10 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -s 10.0.20.10 -d 10.0.20.50 -p tcp --sport 22 -j ACCEPT

# Allow crons
iptables -A INPUT -i enp0s8 -d 10.0.10.10 -p tcp --dport 11061 -j ACCEPT
iptables -A OUTPUT -s 10.0.10.10 -p tcp --sport 11061 -j ACCEPT

/bin/crons > /var/log/crons.log 2>&1 &
python3 /var/www/core/flask_server.py > /var/log/Flask.log 2>&1 