#!/bin/bash
# IPs
ifconfig enp0s3 192.168.1.20 netmask 255.255.255.0 up
ip route add 10.0.10.10 via 192.168.1.40
ip route add 10.0.20.50 via 192.168.1.40

# IP tables
iptables -F
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#Allow SFTP connetions to Backup Server
iptables -A INPUT -i enp0s3 -s 10.0.20.50 -d 192.168.1.20 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -s 192.168.1.20 -d 10.0.20.50 -p tcp --sport 22 -j ACCEPT

#Allow http request to Core Server
iptables -A OUTPUT -s 192.168.1.20 -d 10.0.10.10 -p tcp --dport 10443 -j ACCEPT
iptables -A INPUT -i enp0s3 -s 10.0.10.10 -d 192.168.1.20 -p tcp --sport 10443 -j ACCEPT

#Allow https request from Client
iptables -A OUTPUT -s 192.168.1.20 -p tcp --sport 443 -j ACCEPT
iptables -A INPUT -i enp0s3 -d 192.168.1.20 -p tcp --dport 443 -j ACCEPT

#Allow https request from Client
iptables -A OUTPUT -s 192.168.1.20 -p tcp --sport 80 -j ACCEPT
iptables -A INPUT -i enp0s3 -d 192.168.1.20 -p tcp --dport 80 -j ACCEPT

# Allow SSH
iptables -A INPUT -i enp0s3 -d 192.168.1.20 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -s 192.168.1.20 -p tcp --sport 22 -j ACCEPT

# Allow Localhost
iptables -A INPUT -s 127.0.0.1 -j ACCEPT
iptables -A OUTPUT -d 127.0.0.1 -j ACCEPT

#Run server
service nginx start 
su ubuntu -c "python3 /var/www/webserver/webserver_flask.py > /var/log/Flask.log 2>&1"